import * as child_process from 'child_process';
import { writeFileSync } from 'fs';
import * as util from 'util';

const exec = util.promisify(child_process.exec);

async function createVersionsFile(filename: string) {
  const revision = (await exec('git rev-parse HEAD')).stdout.toString().trim().substring(0, 8);
  const branch = (await exec('git rev-parse --abbrev-ref HEAD')).stdout.toString().trim();
  const revisionDate = (await exec('git show -s --format=%ci HEAD')).stdout.toString().trim().substring(0, 16);

  console.log("Criando o arquivo de versão.");

  const content =
`// this file is automatically generated by git.version.ts script
export const versions = {
  revisionDate: '${revisionDate}',
  revision: '${revision}',
  branch: '${branch}'
};
`;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('src/environments/versions.ts');
