export enum Modulos{
       HOME 							                  = 'HOME'
     , ASSOCIADO                            = 'ASSOCIADO'
     , ADMINISTRATIVO                       = 'ADMINISTRATIVO'
     , CONFIGURACOES                        = 'CONFIGURACOES'
     , GRUPO_ACESSO                         = 'GRUPO_ACESSO'
     , USUARIO                              = 'USUARIO'
     , USUARIOS                             = 'USUARIOS'
     , ALTERAR_SENHA                        = 'ALTERAR_SENHA'
     , PARAMETROS                           = 'PARAMETROS'
     , MINHA_CONTA                          = 'MINHA_CONTA'
     , CLINICAS_ESPECIALIDADES              = 'CLINICAS_ESPECIALIDADES'
     , PERFIL_ASSOCIADO                     = 'PERFIL_ASSOCIADO'
     , DASHBOARD                            = 'DASHBOARD'
     , MANTER_CLINICAS                      = 'MANTER_CLINICAS'
     , ASSOCIADOS                           = 'ASSOCIADOS'
     , IMPRESSAO_CARTAO                     = 'IMPRESSAO_CARTAO'
     , VOUCHER                              = 'VOUCHER'
     , TIPO_ESPECIALIDADE                   = 'TIPO_ESPECIALIDADE'
     , ESPECIALIDADE                        = 'ESPECIALIDADE'
     , CORRETOR                             = 'CORRETOR'
     , AUTORIZACAO_GATEWAY                  = 'AUTORIZACAO_GATEWAY'
     , VALIDAR_CARTAO                       = 'VALIDAR_CARTAO'

}
