export enum Rotas {
    GRUPO_ACESSO                    = 'api/gruposacessos/',
    PESSOA_FISICA                   = 'api/pessoafisica/',
    USUARIO                         = 'api/usuario/',
    UNIDADE                         = 'api/unidade/',
    PERFIL_ACESSO                   = 'api/perfilacesso/',
    PERFIL_ACESSO_USUARIO           = 'api/perfilacessousuario/',
    GRUPO_MODULO                    = 'api/grupomodulo/',
    MODULO                          = 'api/modulo/',
    CONTA_ASSOCIADO                 = 'api/contaassociado/',
    CLINICAS                        = 'api/clinicas/',
    IMPRESSAO_CARTAO                = 'api/impressaocartao/',
    CLINICA_TIPO_ESPECIALIDADE      = 'api/clinicastipoespecialidade/',
    TIPO_ESPECIALIDADE              = 'api/tipoespecialidades/',
    ASSOCIADOS                      = 'api/associados/',
    DEPENDENTE_TITULAR              = 'api/dependentestitular/',
    HISTORICO_PAGAMENTO             = 'api/historicospagamentos/',
    VOUCHER                         = 'api/voucher/',
    TITULAR                         = 'api/titular/',
    CARTAO                          = 'api/cartao/',
    CORRETOR                        = 'api/corretores/',
    AUTORIZACAO_GATEWAY             = 'api/pagseguro/split/autorizacao/',
    PROCEDIMENTO_ASSOCIADO_CLINICA  = 'api/procedimentos/',
    ASSINATURAS                     = 'api/assinaturas/',
}
